name: Laravel Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql

      - name: Install Dependencies
        run: |
          cd project
          composer install

      - name: Copy .env.example to .env
        run: |
          cd project
          cp .env.example .env

      - name: Generate Application Key
        run: |
          cd project
          php artisan key:generate

      - name: Run Tests
        run: project/vendor/bin/phpunit

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: ./tests/TestResults.xml
